omod/src/main/webapp/admin/dictionary/index.jsp, omod/src/main/webapp/dictionary/index.jsp, omod/src/test/java/org/openmrs/web/servlet/DownloadDictionaryServletTest.java
Updated servlet path to point to legacyui: /moduleServlet/legacyui
=> LUI-46: Fix path for download dictionary servlet

omod/src/main/java/org/openmrs/web/controller/ForgotPasswordFormController.java, omod/src/test/java/org/openmrs/web/controller/ForgotPasswordFormControllerTest.java, omod/src/test/resources/org/openmrs/web/controller/include/ForgotPasswordFormControllerTest.xml
This is the Final Fix for the Leakage of Usernames that was occurring when a user clicked on the 'forgotPassword' link. 
https://issues.openmrs.org/browse/LUI-45
<br>
**In light of recent comments on the ticket, it has come to notice that this is a serious security issue and must be resolved ASAP. If you see the comments, you will notice that this code fixes the issue as per ticket description and quite well in general.**
<br>
**The Issue**: Whenever a hacker enters the name of a random user, and the user is valid, his/her secret question is shown. This is a major vulnerability that had to be addressed.
**The Fix:** The solution is to ask ANY user a secret question. If the user is invalid, a random Fake Secret Question is asked whose answer is always false and will not the user pass, …
=> FINAL fix addressing security issues in LUI-45 [Forgot Password Form Leaks Valid Usernames]

omod/src/main/java/org/openmrs/web/controller/LoginController.java
Issue: [[LUI 60] login.htm Should redirect to previous/home page if logged in in legacy UI](https://issues.openmrs.org/browse/LUI-60)<br>
If the User is Authenticated, then he should be redirected to his/her OpenMRS home page and should not be allowed the access the login page
=> Redirecting Authenticated User to home if user tries to access 'login.htm' page [LUI-60]

api/src/main/resources/messages.properties, omod/src/main/java/org/openmrs/web/controller/user/UserFormController.java, omod/src/main/webapp/admin/users/userForm.jsp, omod/src/test/java/org/openmrs/web/controller/user/UserFormControllerTest.java, omod/src/test/resources/org/openmrs/web/controller/include/UserFormControllerTest.xml
Fix for [TRUNK-4734/LUI-65](https://issues.openmrs.org/browse/LUI-65): Implement a new CheckBox which when selected creates a Provider Account for the user being created in user.form
[Image1](https://issues.openmrs.org/secure/attachment/44399/final.jpg)
[Image2](https://issues.openmrs.org/secure/attachment/44398/final2.jpg)
=> TRUNK-4734/LUI-65 Implement a new CheckBox which when selected creates a Provider Account for the user being created in user.form

omod/src/main/resources/config.xml, omod/src/main/webapp/tags/providerField.tag
Orderer input field no longer loses data after form error messages. The Oderer is now populated with the data the user had previously typed before clicking "Save Order".
Changed provider.name to provider.displayName in providerField.tag. Additionally added the getProvider method for DWRProviderService in the config.xml file
=> RAD-151 radiolgyOrderForm looses Orderer on error

omod/src/main/java/org/openmrs/web/controller/patient/PatientDashboardController.java, omod/src/test/java/org/openmrs/web/controller/patient/PatientDashboardControllerTest.java
PatientDashboardController can now be reached with request param patientId values of patientId and UUID
Enables developers using REST where UUID as common to navigate to this page
* extract getPatient method for patient id and uuid
* add test class
see https://issues.openmrs.org/browse/LUI-78
=> LUI-78 Enable use of uuid as patientId param in patientDashboard

omod/src/main/java/org/openmrs/web/attribute/handler/RegexValidatedTextDatatypeHandler.java, omod/src/test/java/org/openmrs/web/attribute/handler/RegexValidatedTextDatatypeHandlerTest.java
RegexValidatedTextDatatype is not validated for when setting a global property
datatype to it since now handler exists. This prevents using regex for
validation of global properties.
* added RegexValidatedTextDatatypeHandler with tests
see https://issues.openmrs.org/browse/LUI-81
=> Add RegexValidatedTextDatatypeHandler

omod/src/main/java/org/openmrs/web/dwr/DWRConceptService.java, omod/src/test/java/org/openmrs/web/dwr/DWRConceptServiceTest.java, omod/src/test/resources/org/openmrs/web/dwr/include/DWRConceptServiceTest-coded-concept-with-no-answers.xml
Changed the data structure that holds Concept Results from `List` to `Set` since `Set` only allows for unique results.
=> TRUNK-4846: Search by ID displays double results

omod/src/main/webapp/errorhandler.jsp
On error in a jsp file the errorhandler page should nicely handle exceptions
for better user experience, however the taglib include was pointing to the
older path when the legacy ui was still part of the core.
* changed taglib uri to same value as in the (omod/src/main/webapp/template/include.jsp)
see https://issues.openmrs.org/browse/LUI-95
=> LUI-95 errorhandler.jsp cannot find openmrs taglib

omod/src/main/webapp/template/gutter.jsp
"Find Patient" navigation bar/link shows for users that do not have the "View
Patients" privilege. When clicking on it the user just gets redirected to a
page telling him he does not have the privilege to access the page.
* Wrap "Find/Create Patient" navigation bar/link with hasPrivilege
"View Patients" to prevent showing "Find Patient" to a user that doesnt have
the privilege.
see https://issues.openmrs.org/browse/LUI-86
=> LUI-86 Show findpatient nav link only with privilege

api/pom.xml, api/src/main/java/org/openmrs/module/legacyui/LegacyUIActivator.java, omod/pom.xml, omod/src/main/java/org/openmrs/web/WebComponentRegistrar.java, omod/src/main/java/org/openmrs/web/attribute/handler/RegexValidatedTextDatatypeHandler.java, omod/src/main/java/org/openmrs/web/controller/concept/ConceptAttributeTypeFormController.java, omod/src/main/java/org/openmrs/web/controller/encounter/EncounterIndexController.java, omod/src/main/java/org/openmrs/web/controller/patient/FindDuplicatePatientsController.java, omod/src/main/java/org/openmrs/web/controller/patient/ManagePatientController.java, omod/src/main/java/org/openmrs/web/controller/patient/PatientDashboardController.java, omod/src/main/java/org/openmrs/web/controller/person/PersonController.java, omod/src/main/java/org/openmrs/web/controller/provider/ManageProviderController.java, omod/src/main/java/org/springframework/web/servlet/mvc/AbstractFormController.java, omod/src/main/java/org/springframework/web/servlet/mvc/AbstractWizardFormController.java, omod/src/main/java/org/springframework/web/servlet/mvc/BaseCommandController.java, omod/src/main/java/org/springframework/web/servlet/mvc/SimpleFormController.java, omod/src/main/resources/config.xml, omod/src/main/resources/webModuleApplicationContext.xml, omod/src/test/java/org/openmrs/web/controller/patient/PatientDashboardControllerTest.java, pom.xml
* use com.mycila maven license plugin
takes license-header.txt from this repo and updates .txt/.xml/.java files
* runs in root/api/omod
* runs by default plugin goal format which formats the headers if not properly
formatted or missing
* when environment variable CI=true it will it will run goal "check" which
fails the build if a header is missing or not properly formatted
try for yourself(change a header or delete one):
formatting
```
mvn formatter:format
```
check
```
mvn formatter:check
```
simulate being on travis CI
```
export CI=true
mvn clean install -DskipTests
```
simulate being a dev :bowtie: 
```
export CI=false
mvn clean install -DskipTests
```
see https://issues.openmrs.org/browse/LUI-87
=> LUI-87 Use maven license plugin

.travis.yml, README.md, omod/pom.xml, pom.xml
* add jacoco maven plugin for generating coverage reports
* add coveralls maven plugin to send jacoco reports to coveralls.io
* add travis after_success command to send jacoco reports to coveralls.io after
successful builds
* jacoco and coverals are configured in root pom pluginmanagement
* jacoco only generates coverage for omod/ for now since there are no tests in
api/
see https://issues.openmrs.org/browse/LUI-96
TRY:
you can locally get the coverage report with:
```
mvn clean install jacoco:report
```
should run tests, prepare jacoco and generate omod/target/site/jacoco
with an index.html where you can see the unit test coverage report.
TODO:
hopefully after the first run on travis CI the project will show up at:
https://coveralls.io/github/openmrs/openmrs-module-legacyui
the maven …
=> LUI-96 Add github PR integration for test coverage

omod/src/main/webapp/portlets/patientHeader.jsp
make an anchor out of the patient name if not on the patientDashboardForm
so users can easily navigate to the patients dashboard.
see https://issues.openmrs.org/browse/LUI-93
=> LUI-93 Add link to patientDashboard in patientHeader portlet

omod/src/main/webapp/admin/concepts/conceptReferenceTermForm.jsp
conceptReferenceTermForm.jsp requires only "Manage Concept Reference Terms"
but if accessing the page with a user with that privilege the page doesnt show
the actual form to enter/see existing reference terms.
* add the privilege "Get Concept Map Types" since it is required as well
see https://issues.openmrs.org/browse/LUI-101
=> LUI-101 conceptReferenceTermForm misses required privilege

omod/src/main/webapp/admin/concepts/conceptDrugForm.jsp, omod/src/main/webapp/admin/concepts/conceptDrugList.jsp, omod/src/main/webapp/admin/concepts/conceptProposalForm.jsp, omod/src/main/webapp/admin/concepts/conceptProposalList.jsp, omod/src/main/webapp/admin/concepts/conceptSetDerivedForm.jsp, omod/src/main/webapp/admin/dictionary/concept.jsp, omod/src/main/webapp/admin/dictionary/conceptStatsForm.jsp, omod/src/main/webapp/dictionary/concept.jsp, omod/src/main/webapp/dictionary/conceptStatsForm.jsp
"Edit Concepts" seems to be a very old privilege that has been replaced by
"Manage Concepts" maybe in ~2008 in the openmrs-core.
* replace occurences of "Edit Concepts" in jsp require tags with "Manage Concepts"
this also seems to fix the LUI-97 bug "Cannot create new conceptSource"
see https://issues.openmrs.org/browse/LUI-100
=> LUI-100 Privilege "Edit Concepts" does not exist

omod/src/main/webapp/admin/dictionary/conceptSidebar.jsp, omod/src/main/webapp/dictionary/conceptSidebar.jsp
conceptForm.jsp includes conceptSidebar.jsp and only requires privilege "Manage
Concepts" altough privileges
"Get Forms"
"Get Observations"
"Get Patient Programs"
are needed to show the concepts stats. Page shows APIAuthorizationException if
one is missing.
* add hasPrivilege tag around code related to concept stats in the
conceptSidebar so it just doesnt show and conceptForm loads fine showing the
concept.
see https://issues.openmrs.org/browse/LUI-102
=> LUI-102 Hide concept stats in conceptSidebar if not allowed

omod/src/main/java/org/openmrs/web/controller/patient/ShortPatientFormValidator.java
use the PersonNameValidator.validate coming from the Validator
interface since validatePersonName is deprecated in core 2.2.0
PersonNameValidator.validate itself calls
validatePersonName(personName, errors, false, true)
the behavior does not change through this change
see https://issues.openmrs.org/browse/TRUNK-5174
=> TRUNK-5174 Deprecate PersonNameValidator.validatePersonName

omod/src/main/webapp/resources/css/openmrs.css
Continuation From:
https://github.com/openmrs/openmrs-module-legacyui/pull/84
Why?
Change Of Branch (Master -> LUI-126)
https://issues.openmrs.org/browse/LUI-126
Fixes Use Of CSS Wildcard Selector and Moves It All to the main HTML {} Tag
=> LUI-126: Wildcard selector * is being used in openmrs.css

omod/src/main/webapp/admin/concepts/conceptProposalForm.jsp
See https://issues.openmrs.org/browse/LUI-66
=> [LUI-66] Concept Proposal Form is broken

omod/src/main/java/org/openmrs/web/attribute/handler/SerializingFieldGenDatatypeHandler.java, omod/src/test/java/org/openmrs/web/attribute/handler/SerializingFieldGenDatatypeHandlerTest.java
Issue: https://issues.openmrs.org/browse/LUI-128
=> LUI-128 Add new Provider Attribute Type

api/src/main/java/org/openmrs/module/legacyui/GeneralUtils.java, omod/src/main/java/org/openmrs/web/controller/PortletController.java, omod/src/main/java/org/openmrs/web/taglib/functions/Filter.java, omod/src/main/webapp/taglibs/openmrs.tld, omod/src/main/webapp/tags/mostRecentObs.tag
@mogoodrich , the changes below fix the legacy Admin UI in all our PIH servers. It continues to support specifying concepts via Integers. So, now it works with either UUIDs or Integers as values for GP concepts. Thanks for reviewing.
=> LUI-155, add support for configuring GP concepts with UUIDs

omod/src/main/java/org/openmrs/notification/web/controller/AlertFormController.java
**Description of what I changed**
The already scheduled users need not be scheduled again.  So, had to remove the already scheduled users.
**Issue I worked On**
see https://issues.openmrs.org/browse/LUI-161
=> LUI-161, Unable to edit the created alert in Users section

omod/src/main/webapp/admin/users/roleList.jsp
**Ticket:** [LUI-173](https://issues.openmrs.org/browse/LUI-173)
**Description:** Changed the href link on Role Management section to properly encode the role name that is passed as an URL parameter.
=> LUI-173: Encoding of single role link URL on roleList.jsp.

omod/src/main/webapp/resources/scripts/dojo/src/widget/openmrs/OpenmrsSearch.js
@annaowens
Fixed the HTML parsing in `OpenmrsSearch.js` to read users' search input as text rather than HTML. 
_Note_: I did not fight many documented fixes of vulnerabilities in `.js` files, so I modeled this fix after [this PR](https://github.com/openmrs/openmrs-module-legacyui/pull/87/files). Please let me know if a different technique to fix the vulnerability is preferred. This is also my first PR to OpenMRS, so let me know if if you have any suggestions to improve the PR format in general. Thanks!
This fix protects against reflected XSS in the search results on the Admin's Manage Fields page (in Advanced Administration).
**Before Fix**
**After Fix**
1. Launch OpenMRS application.
2. Login with username "Admin" and password "Admin123" with location as Inpatient Ward.
3. Select “System …
=> EMPT-48: Fixed XSS vulnerability in Manage Fields list

omod/src/main/webapp/admin/users/users.jsp
@isears 
Fixed `users.jsp` to interpret the user roles (specifically when searching for users in User Management) as as text rather than as HTML. 
This fix protects against reflected XSS that is inputted into the title of a new user role. When the role is assigned to a user and that user is searched in the Manage Users tab of Advanced administration, the script is interpreted as HTML rather than text.  
_Note:_ Without the additional `c:out` tag on line 93 of `users.jsp`, a role with an XSS title will sometimes cause the `title` attribute to be vulnerable to XSS injection.
Pop-ups with the message from the injected script tag:  
User role is not shown in the UI as it is part of the HTML:   
User role is now shown as text rather than interpreted …
=> Fixed XSS vulnerability in roles field of user list

omod/src/main/webapp/admin/person/include/editPersonInfo.jsp, omod/src/main/webapp/admin/person/personForm.jsp
Added c:out for the person and patient voidReason in editPersonInfo and personVoidReason in personForm
Sanitized input for the reason you delete a person in the legacyui. The script would be executed twice because it gets reference twice when you delete but now will not be executed with this patch.
It can be reproduced following 
1. Launch OpenMRS application using the URL: http://localhost:8800/openmrs
2. Provide the following info and click login​Username​ as ​admin​ Password​ ​ as ​admin123 Location as ​Inpatient
3. Click on the tiles in this order: System Administration ‹ Advanced Administration.
4. Under the Person category, click on Manage Persons, and on the page that appears, click on Create Person.
5. Enter the details as prompted and click on the Create Person button.
6. In the …
=> RA-1875: EMPT59  Fixed XSS vulnerability in editPersonInfo and personForm

omod/src/main/java/org/openmrs/web/dwr/DWRConceptService.java
@isears 
Fixed `DWRConceptService.java` to encode the search result phrase that appears when users search for a Question Concept in the `Manage Observations` page.
_Note_: Since `ui` was not defined in this file, I modeled this fix after [this PR](https://github.com/openmrs/openmrs-module-uiframework/pull/52/files) Please let me know if a different technique to fix the vulnerability is preferred!
This fix protects against stored XSS that is inputted into the `Question Concept` search field when creating a Observation. The search widget that appears presents a message which reads "No matches found for {search phrase}", which would reflect XSS in the search phrase when it was submitted as the search phrase. 
Injected iframe appears in search …
=> RA-1865: Fix vulnerable question concept in Manage Observations

omod/src/main/webapp/admin/concepts/conceptProposalList.jsp
@isears 
Fixed the display format of Current Proposed Concept table in `conceptProposalList.jsp` to display the Proposed Concept Original Text as text rather than as HTML. 
This fix protects against XSS that is inputted to a new Proposed Concept form. When an iframe or script is entered in the Proposed Concept Form, the html is executed when the new concept appears in the Current Proposed Concept table on the Manage Proposed Concept Page.
Iframe appears in the Current Proposed Concept table:  
Original Text of proposed concept shown as text rather than interpreted as HTML:
1. Launch the OpenMRS application.
2. Login with username "Admin" and password "Admin123" with location as Inpatient Ward.
3. Select “System Administration”
4. Select …
=> RA-1865: Fix XSS vulnerability in Manage Proposed Concepts

omod/src/main/webapp/template/headerFull.jsp
@isears 
Fixed the display format of alerts in `headerFull.jsp` to display the alert titles as text rather than as HTML. 
This fix protects against reflected XSS that is inputted to an alert title. When a script or other malicious input is inserted, it will be executed as HTML each time a page with the header is loaded for the user to which the alert was assigned. The page is loaded on nearly every legacy UI page. The fix is locaed in the `headerFull.jsp` file, as this file is the one that displays the alert title and is vulnerable to the XSS attack.
Pop-ups with the message from the injected script tag:  
Alert text is not shown as it is part of the HTML now:  
Alert title is now shown as text rather than interpreted as HTML
1. Launch the …
=> EMPT-67: Fixed XSS vulnerability in alert header

omod/src/main/java/org/openmrs/web/dwr/DWRFormService.java
@isears 
Fixed `DWRFormService.java` to encode elements of the `FieldListItem` object before passing it to the UI to display in the search results on the `Manage Fields` page.
_Note_: Since `ui` was not defined in this file, I modeled this fix after [this PR](https://github.com/openmrs/openmrs-module-uiframework/pull/52/files).
This fix protects against stored XSS that is inputted into the `Name` when creating a new Field. After creating the field, when you search that field in the Manage Fields page, the search result table will execute the XSS vulnerability in the results.
Injected iframe appears in search results:
Field name is now shown as text rather than interpreted as HTML:   
1. Launch the OpenMRS application.
2. Login with username …
=> RA-1865: Fix XSS Vulnerability in Manage Fields List

omod/src/main/webapp/resources/scripts/jquery-ui/js/openmrsSearch.js
When building the search results table, I changed `return data` to ` return $j('<div/>').text(data).html()` in order to prevent Iframes from being shown in the person search results.
This is a very similar issue to the one fixed by Anna [here](https://github.com/openmrs/openmrs-module-legacyui/pull/137).
One could create a new person with given name `<iframe src="http://www.ncsu.edu">`. When searching for this person by typing `<iframe`, the results list would display that iframe. In addition, where it says "viewing results for __" would also display a blank iframe.
Searching for `<iframe` when a person with given name `<iframe src="http://www.ncsu.edu">` exists.
Searching for `<iframe` when a person with given name `<iframe …
=> RA-1865 Added HTML escape for search results

omod/src/main/java/org/openmrs/web/dwr/DWRFormService.java
@isears 
Fixed `DWRFormService.java` to encode the `fieldType` and `description` attributes of the `FieldListItem` object before passing it to the UI to display in the search results on the `Manage Fields` page. 
**This change is very similar to [this PR](https://github.com/openmrs/openmrs-module-legacyui/pull/153) and probably should have been fixed there had I realized this were a vulnerability. I went ahead and tested the Description column for a vulnerability as well, and it had one that I fixed (again, should have been fixed in the first PR).
_Note_: Since `ui` was not defined in this file, I modeled this fix after [this PR](https://github.com/openmrs/openmrs-module-uiframework/pull/52/files).
This fix protects against stored XSS that is …
=> RA-1865: Fix XSS vulnerability in Field Type and Description of Manage Fields

omod/src/main/java/org/openmrs/web/controller/maintenance/ServerLogController.java
@isears one of our listed vulnerabilities was that no logging occurs when a user views the server log. This should be a simple fix.
=> Logging when user accesses server log

omod/src/main/java/org/openmrs/web/dwr/DWREncounterService.java
@isears 
Fixed `DWREncounterService.java` to encode the search result phrase that appears when users search for an encounter to add in the `Edit Visit` page.
_Note_: Since `ui` was not defined in this file, I modeled this fix after [this PR](https://github.com/openmrs/openmrs-module-uiframework/pull/52/files).
This fix protects against reflected XSS that is executed when a user searches for an encounter to add on the Edit Visit page. Specifically, this vulnerability fixes the vulnerability that occurs when no search results match the search phrase. The search widget that appears presents a message which reads "No matches found for {search phrase}", which reflects XSS in the search phrase. 
Injected iframe appears in search message:
Search …
=> RA-1865: Fix XSS in Add Encounter to Visit

omod/src/main/java/org/openmrs/web/dwr/DWRPersonService.java, omod/src/main/webapp/resources/scripts/jquery-ui/js/openmrsSearch.js
Link to ticket
Reverted the changes for https://github.com/openmrs/openmrs-module-legacyui/pull/152 and add a serverside fix.
The issue I worked on
One could create a new person with given name <iframe src="http://www.ncsu.edu">. When searching for this person by typing <iframe, the results list would display that iframe. In addition, where it says "viewing results for __" would also display a blank iframe.
Before fix
Searching for <iframe when a person with given name <iframe src="http://www.ncsu.edu"> exists.
image
After fix
Searching for <iframe when a person with given name <iframe src="http://www.ncsu.edu"> does not exists.
image
Steps to reproduce
Login to OpenMRS as admin.
Go to System Admininstration > Advanced Administration > Manage …
=> Changed DWRPersonService for EMPT60

omod/src/main/java/org/openmrs/web/dwr/ProviderListItem.java, omod/src/main/webapp/resources/scripts/jquery-ui/js/openmrsSearch.js
Had raised https://github.com/openmrs/openmrs-module-legacyui/pull/141 for the following. After which @isears requested to modify the server-side code instead of the JS files. So I tried solving EMPT64 with changes in the following server File:- omod/src/main/java/org/openmrs/web/dwr/ProviderListItem.java. Had to revert the changes of the following PR https://github.com/openmrs/openmrs-module-legacyui/pull/152 to make it error free. 
Steps to reproduce can be found here.
https://docs.google.com/document/d/1GJNMRlGTRV45St6WSjnD_FjW84aoNxY9HzGbpwoBrro/edit?usp=sharing
Link to ticket:
=> Added WebUtil.escapeHTML function to ProviderListItem

omod/src/main/java/org/openmrs/web/dwr/DWRUserService.java
Hi Team,
This change is for fixing EMPT80. I have performed minor test runs to the best of my abilities.
@isears @sherrif10 
Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)
Steps to reproduce :
1)Launch OpenMRS application using the URL: http://localhost:8080/openmrs
2) Provide following info and click login​Username​ as ​admin​ Password​ ​ as ​admin123 Location as ​Inpatient
3) Click on the “System Administration” module.
4) Click on “Manage Accounts”.
5) Click on the “Add New Account” button.
6) Enter <iframe src=’http://ncsu.edu’> as First Name and Last Name and select Male as Gender.
7) Click on the “Add User Account?” checkbox.
8) Enter “testtest” as Username and select Full as Privilege Level.
9) Enter Admin123 as Password and Confirm Password.
10) Hit Save.
11) …
=> Made chanes to fix EMPT80

omod/src/main/webapp/template/headerFull.jsp, omod/src/main/webapp/template/headerMinimal.jsp
Hi Team,
Steps to reproduce. Worked together with @kfb19 to achieve this fix.
1) Go to "Manage Privileges" and add a new privileged named <script>alert(1);</script> (this is harmless by itself)
2) Delete that privilege.
3)Get the alert box.
1) Similarly Create a role named <script>alert(1);</script>.
2) Delete that role.
3) Get the alert box.
Will be adding the before and after fix soon.
Here's the link to the ticket.
Link to ticket
@isears @sherrif10 
Thanks,
Parth
=> Made changes to fix EMPT176

omod/src/main/webapp/dictionary/concept.jsp
- Retired Answer Concepts show HTML code in the list 
screenshots
@dkayiwa , @ibacher
=> [LUI-48]: Retired Answer Concepts show HTML code in the list

omod/src/main/java/org/openmrs/web/servlet/LoginServlet.java
After TRUNK-6203, users must possess the 'Get Global Properties' privilege to access global properties. This addition and removal of the global property are necessary for accessing global properties before a user logs in.
Ticket: https://openmrs.atlassian.net/browse/TRUNK-6203
=> TRUNK-6203: Global properties access should be privileged
