omod/src/main/java/org/openmrs/web/controller/FieldGenController.java
omod/src/main/java/org/openmrs/web/controller/provider/ManageProviderController.java
omod/src/main/java/org/openmrs/web/controller/provider/ProviderAttributeTypeFormController.java
omod/src/main/java/org/openmrs/web/controller/provider/ProviderAttributeTypeListController.java
omod/src/main/java/org/openmrs/web/controller/provider/ProviderFormController.java
omod/src/main/resources/webModuleApplicationContext.xml
omod/src/test/java/org/openmrs/web/controller/provider/ProviderFormControllerTest.java

…rm pages
add provider.form
add field generation for provider form
move test for providerformcontroller

LUI-22: Add support for provider admin pages

---

omod/src/main/resources/webModuleApplicationContext.xml
omod/src/test/java/org/openmrs/scheduler/web/controller/SchedulerFormControllerTest.java
omod/src/test/java/org/openmrs/scheduler/web/controller/SchedulerFormTest.java
omod/src/test/resources/org/openmrs/web/include/SchedulerFormControllerTest.xml

LUI-9: add SchedulerFormTest and SchedulerFormControllerTest
LUI-9: fix formView paths for scheduler list and form controllers

LUI-9: uncomment controllers and mappings

---

omod/src/main/resources/webModuleApplicationContext.xml

PR for issue at: https://issues.openmrs.org/browse/LUI-10

LUI-10: Migrate Legacy Programs Admin

---

omod/src/main/resources/webModuleApplicationContext.xml

PR for: https://issues.openmrs.org/browse/LUI-12

LUI-12: Migrate Legacy Forms Admin

---

omod/src/main/java/org/openmrs/web/controller/person/AddPersonController.java
omod/src/main/java/org/openmrs/web/controller/person/PersonAttributeTypeListController.java
omod/src/main/java/org/openmrs/web/controller/person/PersonController.java
omod/src/main/resources/webModuleApplicationContext.xml

LUI-3: add PersonController
LUI-3: Fix view for addPerson.htm page, fix URL paths for AddPersonController redirects
LUI-3: add support for person relationship types and type views
LUI-3: fix view name in PersonAttributeTypeListController
LUI-3: fix view for personattributetypeform

LUI-3: Support Person admin screens

---

omod/src/main/java/org/openmrs/hl7/web/controller/Hl7InArchiveListController.java
omod/src/main/java/org/openmrs/hl7/web/controller/Hl7InArchiveMigrationController.java
omod/src/main/java/org/openmrs/hl7/web/controller/Hl7InErrorListController.java
omod/src/main/java/org/openmrs/hl7/web/controller/Hl7InQueueListController.java
omod/src/main/resources/webModuleApplicationContext.xml
omod/src/main/webapp/admin/hl7/localHeader.jsp

Modified URL mapping for admin/hl7/hl7ErrorsInList.htm to admin/hl7/hl7Errors.htm
PR for: https://issues.openmrs.org/browse/LUI-13

LUI-13: Migrated Legacy HL7 Admin

---

omod/src/main/webapp/admin/patients/shortPatientForm.jsp

Same as [TRUNK-4814](https://issues.openmrs.org/browse/TRUNK-4814) which is already resolved.
**Issue**: [LUI-32](https://issues.openmrs.org/browse/LUI-32?jql=labels%20%3D%20community-priority%20AND%20status%20%3D%20%22In%20Progress%22)
**Fix**: fixed by replacing form select with spring bind tag

Fix for Error creating patient for large location IDs > 1000 [LUI-32]

---

.gitignore
.travis.yml

Add .travis.yml to ensure new PRs do not break the build.

Add travis.yml for PR integration

---

omod/src/main/webapp/taglibs/spring-form.tld
omod/src/main/webapp/taglibs/spring.tld

* update spring.tld from version 1.1.2 to 4.0
* update spring-form.tld from version 2.5 to 4.0
both taglibs were copied from the org.springframework:spring-webmvc:4.1.4.RELEASE
which is the version the openmrs 2.0.x is based on
see https://issues.openmrs.org/browse/LUI-88

LUI-88 Update spring taglibs

---

omod/src/main/java/org/openmrs/web/taglib/PrivilegeTag.java
omod/src/main/webapp/taglibs/openmrs.tld
omod/src/test/java/org/openmrs/web/taglib/PrivilegeTagTest.java
omod/src/test/resources/org/openmrs/web/taglib/include/PrivilegeTagTest.xml

* add attribute "hasAll" to openmrs tag "hasPrivilege"
* add dataset xml with tests
* add javadocs to class and methods
* refactor code in doStartTag
* extract private helper methods to check if privilege conditions satisfy
* use java's Boolean.valueOf("true") to parse inverse/hasAll attribute values
see https://issues.openmrs.org/browse/LUI-94

LUI-94 Extend hasPrivilege tag to ensure user has all privileges

---

omod/src/main/webapp/admin/users/localHeader.jsp
omod/src/main/webapp/admin/visits/localHeader.jsp

This PR is dependency for https://github.com/openmrs/openmrs-distro-referenceapplication/pull/166

RA-1210 - Added IDs to Visits management links

---

omod/src/main/webapp/admin/modules/localHeader.jsp

This PR is dependency for: https://github.com/openmrs/openmrs-distro-referenceapplication/pull/193

RA-1236 - Added ID to Manage Modules link

---

omod/src/main/webapp/errorhandler.jsp
omod/src/main/webapp/template/include.jsp

uri's pointing to /WEB-INF/taglibs should point to the legacyui module's folder i.e
/WEB-INF/view/module/legacyui/taglibs

LUI-95 Point taglib uri's in jsps to legacyui

---

omod/src/main/webapp/authorizationHandlerInclude.jsp
omod/src/main/webapp/uncaughtException.jsp

https://issues.openmrs.org/browse/RA-974

RA-974 do not log stack trace when non-authenticated user tries to access page

---

omod/src/main/java/org/openmrs/web/dwr/DWRPatientService.java
omod/src/main/java/org/openmrs/web/dwr/PatientListItem.java
omod/src/main/resources/config.xml
omod/src/main/webapp/admin/patients/findDuplicatePatients.jsp
omod/src/test/java/org/openmrs/web/dwr/DWRPatientServiceTest.java
omod/src/test/resources/org/openmrs/web/dwr/include/DWRPatientService-findByIdentifier.xml

Ability to search for patients to merge by identifiers

LUI-108 | Ability to search for patients to merge by identifiers

---

omod/src/main/java/org/openmrs/web/controller/patient/MergePatientsFormController.java
omod/src/main/webapp/admin/patients/mergePatientsForm.jsp

https://issues.openmrs.org/browse/LUI-115
Old PR https://github.com/openmrs/openmrs-module-legacyui/pull/74.

LUI-115 | Able to merge patients with discontinued orders

---

omod/src/main/java/org/openmrs/module/web/controller/ModuleListController.java

Ensuring the Spring context has been refreshed before filters get loaded in case filters need dependencies defined in the Spring context. Previously, filters would be loaded before the Spring context was refreshed. This would lead to issues when the filters had a class of org.springframework.web.filter.DelegatingFilterProxy, meaning Spring is supposed to resolve all dependencies of the filter. If the context had not been refreshed, no beans would be found.
Additionally, an issue was also occurring when no "dwr-invoker" servlet was present, so made the reInitServlet only called if a servlet was present.
See this discussion on OpenMRS Talk for more clarification.
https://talk.openmrs.org/t/loading-modules-error-due-to-filters-and-spring-beans/14162
Here is the link to the JIRA item. …

LUI-133: Fix error on module load when module uses Spring-injected filters

---

omod/src/main/webapp/resources/scripts/jquery/autocomplete/OpenmrsAutoComplete.js

Patch issue from this thread: https://talk.openmrs.org/t/xss-vulnerability-in-adduser-form-openmrs-2-6-1-legacy-module-1-3-3/14698

RA-452: html-encode autocomplete results

---

omod/src/main/java/org/openmrs/web/controller/observation/ObsFormController.java

Issue: https://issues.openmrs.org/browse/LUI-134

[LUI-134] NullPointerException when voiding Observation

---

omod/src/main/webapp/portlets/patientGraphs.jsp

Issue: https://issues.openmrs.org/browse/LUI-130
I've already tested it on OpenMRS instance and now it's displaying the graph correctly.

[LUI-130] Graphs do not display in the patient Graphs section

---

omod/src/main/webapp/admin/person/include/editPersonInfo.jsp

Ticket: https://issues.openmrs.org/browse/LUI-137

LUI-137:Removed trailing quatation on the uuid field in personInfo tab

---

omod/src/main/webapp/portlets/nameLayout.jsp

Ticket: https://issues.openmrs.org/browse/LUI-142
I have removed the mandatory notation ("*") for the family name since the family name is not compulsory to a patient details

LUI-142 : Removed required * notation for the family name

---

.travis.yml
omod/src/main/java/org/openmrs/web/WebComponentRegistrar.java

link:https://issues.openmrs.org/browse/LUI-151

LUI-151:Logout Button not working in demo

---

omod/src/main/java/org/openmrs/web/controller/user/UserFormController.java
omod/src/main/webapp/admin/users/userForm.jsp
omod/src/test/java/org/openmrs/web/controller/user/UserFormControllerTest.java

[LUI-156](https://issues.openmrs.org/browse/LUI-156)
1. Add extension point for location 
2. Fix response code on error in userFormController
Openmrs Talk: https://talk.openmrs.org/t/fix-response-status-code-in-userformcontroller-of-openmrs-legacyui/27251/6

LUI-156: Custom extension on user form | Fix error response code in UserFormController.

---

omod/src/main/java/org/openmrs/template/web/controller/FooterFullController.java
omod/src/main/webapp/resources/css/openmrs.css
omod/src/main/webapp/template/footer.jsp
omod/src/main/webapp/template/footerFull.jsp

https://issues.openmrs.org/browse/LUI-153
Added a controller that helps to pick the extra data from the messages.properties file and the extra data is added to the footerFull.jsp during rendering.
Added screen shorts to the ticket ID plus some comments

LUI-153: Footer to show optional extra data from runtime properties.

---

omod/src/main/resources/config.xml
omod/src/main/webapp/template/headerFull.jsp

https://issues.openmrs.org/browse/LUI-151

LUI-151: Logout button to use LogoutServlet defined in config.xml.

---

omod/src/main/java/org/openmrs/web/WebComponentRegistrar.java

https://issues.openmrs.org/browse/LUI-151

LUI-151: LogoutServlet not added through code anymore.

---

omod/src/main/webapp/patientDashboardForm.jsp

Hi @mseaton , here is the PR for adding Regimens as the second tab on the patient dashboard.

LUI-164, add Regimens as second tab on the patient dashboard

---

omod/src/main/java/org/openmrs/web/dwr/DWRConceptService.java
omod/src/test/java/org/openmrs/web/dwr/DWRConceptServiceTest.java

https://issues.openmrs.org/browse/LUI-123
Added the capability of searching Concepts by Concept UUIDs

LUI-123: Capability of searching Concepts by Concept UUIDs

---

omod/src/main/java/org/openmrs/web/dwr/DWRProgramWorkflowService.java
omod/src/main/resources/config.xml
omod/src/test/java/org/openmrs/web/dwr/DWRProgramWorkflowServiceTest.java
pom.xml

- Added #`getProgramWorkflow` in `DWRProgramWorkflowService.java ` for retrieving a `ProgramWorkflow` by uuid or id
- Modified #`getStatesByWorkflow` to use #`getProgramWorkflow` for getting `ProgramWorkflow`s

LUI-167: Should be able to find a program workflow by id or uuid

---

omod/src/main/webapp/admin/users/localHeader.jsp

https://issues.openmrs.org/browse/LUI-176
cc @k-joseph  @dkayiwa  Kindly review thanks

LUI-176:Fix Typo error in legacyui on admin page

---

omod/src/main/java/org/openmrs/web/dwr/DWREncounterService.java

@isears 
Fixed `DWREncounterService.java` to encode elements of the `EncounterList` object before passing it to the UI to display in the search results on the `Manage Encounters` page.
_Note_: Since `ui` was not defined in this file, I modeled this fix after [this PR](https://github.com/openmrs/openmrs-module-uiframework/pull/52/files) and [this second PR](https://github.com/openmrs/openmrs-module-registrationapp/pull/13/files). Please let me know if a different technique to fix the vulnerability is preferred!
This fix protects against stored XSS that is inputted into the `Name` when creating a new `Encounter Type`. When a new Encounter is created and that Encounter Type is assigned to it, the XSS will be executed if the Encounter appears in the …

RA-1865: Fix XSS vulnerability in encounter list

---

omod/src/main/java/org/openmrs/web/taglib/ListPickerTag.java

By encodingHTML in the name field of the ListPicker, we remove the possibility for XSS in the name field.

EMPT 75: Manage Privileges XSS

---

omod/src/main/java/org/openmrs/web/dwr/DWRConceptService.java
omod/src/main/webapp/resources/scripts/jquery-ui/js/openmrsSearch.js

Link to ticket
Reverted the changes of  #152 and add a serverside fix.
Following are the steps to reproduce EMPT46:
i) "Provide following info and click login​
Username​ as ​admin​ 
Password​ ​ as ​admin123 
Location as ​Inpatient "
ii) Click on “System administration”
Then, click on “Advanced administration”
Click on “Manage Reference Term”
Click on “Add New Reference Term”
iii)"Enter the following information:
Code as “><iframe src=https://www.ncsu.edu> or you can also try <iframe src="https://www.ncsu.edu">
Name as “><iframe src=https://www.ncsu.edu>
Source as PIH
Description as “><iframe src=https://www.ncsu.edu>"
"Related Terms:
Map types as SAME-AS
Sources as Search all sources
Code as “><iframe src=https://www.ncsu.edu>"
iv) GO back one …

Fixed DWRConceptService for EMPT46

---

omod/src/main/webapp/admin/person/relationshipTypeViewForm.jsp

Hi,
Have changed the following file:- omod/src/main/webapp/admin/person/relationshipTypeViewForm.jsp Kindly review and let me know the feedback. 
Worked along with @The-Lady  for solving the issue.
Steps to reproduce :
Launch OpenMRS application using the URL: http://localhost:8800/openmrs
--
Provide following info and click login​Username​ as ​admin​ Password​ ​ as ​admin123 Location as ​Inpatient
Click ‘System Administration’ >>‘Advanced Administration’
Click ‘Manage Relationship Types’ >> ‘Add Relationship Type’
lnput the following information:
Name:  xyz
A is to B: hello
B is to A: <script>alert(1)</script>
Description: des
Click “Save Relationship Type”
Click “Manage Relationship Type Views”
Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)
@isears

Added Fix for EMPT62 by adding cout

---

omod/src/main/java/org/openmrs/scheduler/web/controller/SchedulerFormController.java
omod/src/main/java/org/openmrs/web/dwr/DWRConceptService.java

I added encoding to SchedulerForm java file to prevent XSS vulnerability in Task Name.
An iframe/script could be injected in Task Name while adding a new task in Scheduler. I encoded the name of the task in the controller file to mitigate this.
Steps to reproduce the vulnerability:
1. Launch the OpenMRS application.
2. Login with username "Admin" and password "Admin123" with location as Inpatient Ward.
3. Click on the “System Administration” option and then on "Advanced Administration".
4. Click on “Manage Scheduler”.
5. Click on “Add Tasks”.
6. Enter '<iframe src="https://www.csc.ncsu.edu/">' as Name and “org.openmrs.scheduler.tasks.SendEmailTask” and Schedulable Class.
7. Click on “Save”.
Output: An iframe will be displayed.
[RA-1875](https://issues.openmrs.org/browse/RA-1875)
@isears

RA-1875: EMPT66 Fixed XSS Vulnerability in Schedule Form

---

omod/src/main/webapp/resources/scripts/dojo/src/widget/openmrs/OpenmrsSearch.js

Hi Team,
This fixes EMPT51. There was an milder version of the fix earlier which wasn't able to fix iframes and possiby complex xss injections.  Steps to reproduce .
i) Loop into the manage forms of the Administration page
ii) Select Admission(simple) and Enter the values in the Find field search box at the bottom right corner from the image.
@isears 
Link to Ticket
Before Fix
After Fix :

Fixed EMPT51

---

omod/src/main/webapp/admin/dictionary/index.jsp
omod/src/main/webapp/dictionary/index.jsp

Hi Team,
This change is for fixing EMPT107. I have performed minor test runs to the best of my abilities.
Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)
@isears 
Steps to reproduce :
i) Login in as admin inpatient.
ii) Click on the “Configure Metadata” option.
iii) Click on “Manage Concept Dictionary”.
iv) Click on “Manage Concepts”.
v) Click on “Add New Concept”.
vi) Type in  <iframe src="https://www.csc.ncsu.edu" /> for “Fully Specified Name”, <script>alert(1);</script> for “Short Name”, and <script>alert(3);</script> for “Description”.
vii) Click on “Save Concept”.
viii) Now go to home and then "System administration" -> "Advanced administration"
ix) Click on view concepts dictionary
x) search for <script>
Before fix
After fix

Made changes to fix EMPT107

---

omod/src/main/webapp/admin/users/roleList.jsp

Hi Team,
Here's the link to the ticket. 
Link to ticket
Issue I worked on
Steps to reproduce 
i) Go to "Manage Privileges" and add a new privileged named <script>alert(1);</script> (this is harmless by itself)
ii) Go to "Manage Roles" and assign that privilege to a role (or create a new role).
iii) See the 1 in the alert box
Before Fix 
After fix
@isears @sherrif10 
Thanks

Added changes to roleList.jsp

---

omod/src/main/java/org/openmrs/web/dwr/DWRPatientService.java
omod/src/main/resources/config.xml

Hi @dkayiwa and @mogoodrich , here is the small change I made in the legacyui to bring back this feature. Thanks!

LUI-182, close active programs when exiting from care

---

api/src/main/resources/messages.properties
omod/src/main/webapp/uncaughtException.jsp

Paired with PR https://github.com/openmrs/openmrs-core/pull/4742 in core

resolve 3.4.1 by eliminating access to seeing errors without authentication

---

omod/src/main/webapp/resources/scripts/jquery/autocomplete/OpenmrsAutoComplete.js

This is a followup PR for: https://github.com/openmrs/openmrs-module-legacyui/commit/8c80024f6577bb73a1c8f98064cea407800f52e6

Fix search suggestions display issue

---

omod/pom.xml
omod/src/main/java/org/openmrs/notification/web/dwr/DWRMessageService.java
omod/src/main/java/org/openmrs/web/WebComponentRegistrar.java
omod/src/main/java/org/openmrs/web/dwr/DWRObsService.java
omod/src/main/java/org/openmrs/web/dwr/DWRUserService.java
omod/src/main/java/org/openmrs/web/dwr/OpenmrsDWRServlet.java

Ticket: https://openmrs.atlassian.net/browse/LUI-202

LU-202: Migrate to OpenMRS Contrib DWR
